services:
  linkstack:
    image: linkstackorg/linkstack:latest
    container_name: linkstack
    environment:
      - TZ=America/Chicago
    volumes:
      - ./data:/htdocs/data
    ports:
      - "8090:90" 
    restart: unless-stopped
