services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=n8n
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - cloudflare_net
  n8n:
    build: .
    container_name: n8n
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - TZ=America/Chicago
      - WEBHOOK_URL=https://n8n.rupan.dev/
      - N8N_PUSH_BACKEND=websocket
      - N8N_SECURE_COOKIE=false          
      - N8N_PROXY_HOPS=1
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
      - N8N_HOST=n8n.rupan.dev
      - N8N_PORT=5678
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=password
    volumes:
      - n8n_data:/home/node/.n8n
      - ./media_processing:/home/node/media_processing
    networks:
      - cloudflare_net

volumes:
  n8n_data:
    external: true
networks:
  cloudflare_net:
    external: true
