all:
  vars:
    ansible_python_interpreter: /usr/bin/python3

  children:
    # Group 1: The Bare Metal (Proxmox Nodes)
    proxmox_nodes:
      hosts:
        pve1:
          ansible_host: 10.1.34.50
          ansible_user: root 

    # Group 2: The VMs Terraform Created
    virtual_machines:
      children:
        # Sub-group: Docker Hosts
        docker_swarm:
          hosts:
            manager1:
              ansible_host: 192.168.1.101
            worker1:
              ansible_host: 192.168.1.102
            worker2:
              ansible_host: 192.168.1.103

        pihole_dns:
          hosts:
            pihole-primary:
              ansible_host: 192.168.1.105