tunnel: <tunnel-id>
credentials-file: /home/rupan/.cloudflared/<tunnel-id>.json

ingress:
  - hostname: grafana.rupan.dev
    service: http://localhost:3000
  - hostname: n8n.rupan.dev
    service: http://localhost:5678
  - hostname: glance.rupan.dev
    service: http://localhost:8080
  - hostname: pihole.rupan.dev
    service: http://localhost:80
    originRequest:
      httpHostHeader: pihole.rupan.dev
      noTLSVerify: true
  - hostname: ssh.rupan.dev
    service: ssh://localhost:22
  - service: http_status:404
